const colors = require('tailwindcss/colors');

module.exports = {
  mode: 'jit',
  purge: ['./src/**/*.{js,ts,jsx,tsx}'],
  darkMode: true,
  theme: {
    backgroundSize: {
      auto: 'auto',
      cover: 'cover',
      contain: 'contain',
      setinconfig: '29px',
      16: '4rem',
    },
    backgroundPosition: {
      bottom: 'bottom',
      'bottom-4': 'center bottom 1rem',
      center: 'center',
      left: 'left',
      'left-bottom': 'left bottom',
      'left-top': 'left top',
      'left-center': 'left center',
      right: 'right',
      'right-bottom': 'right bottom',
      'right-top': 'right top',
      top: 'top',
      'top-4': 'center top 1rem',
      'left-topbump': 'left center',
    },
    fontSize: {
      xs: '0.75rem',
      sm: '0.875rem',
      base: '1rem',
      lg: '1.125rem',
      xl: '1.25rem',
      '2xl': '1.5rem',
      '3xl': '1.875rem',
      '4xl': '2.25rem',
      '5xl': '3rem',
      '6xl': '4rem',
    },
    extend: {
      backgroundImage: {
        'hero-background': "url('../public/assets/images/hero-area-bg.jpg')",
        'section-two-background': "url('../public/assets/images/section-two-bg.jpg')",
        'section-three-background':
          "url('../public/assets/images/section-three-bg.jpg')",
        'section-four-background': "url('../public/assets/images/section-four-bg.jpg')",
        'section-five-background': "url('../public/assets/images/section-five-bg.jpg')",
        'section-six-background': "url('../public/assets/images/section-six-bg.jpg')",
        'section-seven-background':
          "url('../public/assets/images/section-seven-bg.jpg')",
        // 'hero-background-right': "url('../public/assets/images/section-seven-bg.jpg')",
        'steel-button': "url('../public/assets/images/button-bg.jpg')",
        'tile-one': "url('../public/assets/images/chart-tile.jpg')",
        'tile-two': "url('../public/assets/images/coin-tile.jpg')",
        'tile-three': "url('../public/assets/images/diamond-hands-tile.jpg')",
        'list-icon': "url('../public/assets/images/list-icon.png')",
        // 'footer-texture': "url('/img/footer-texture.png')",
      },
      colors: {
        black: colors.black,
        white: colors.white,
        indigo: colors.indigo,
        red: colors.rose,
        pink: colors.pink,
        violet: colors.violet,
        amber: colors.amber,
        yellow: colors.amber,
        primary: {
          100: '#E6F6FE',
          200: '#C0EAFC',
          300: '#9ADDFB',
          400: '#4FC3F7',
          500: '#6654F1',
          600: '#0398DC',
          700: '#026592',
          800: '#014C6E',
          900: '#013349',
        },
        gray: {
          100: '#f7fafc',
          200: '#edf2f7',
          300: '#e2e8f0',
          400: '#cbd5e0',
          500: '#a0aec0',
          600: '#718096',
          700: '#4a5568',
          800: '#2d3748',
          900: '#1a202c',
        },
        themePrimary: {
          100: '#ffffff',
          200: '#FBD9AC',
          300: '#EED1AF',
          400: '#6654F1', // default
          500: '#6654F1',
        },
        themePrimaryDark: {
          100: '#11151E',
        },
        themePrimaryAux: {
          100: '#FC634D',
          200: '#F78CBB',
          300: '#FEBE79',
        },
      },
      lineHeight: {
        hero: '4.5rem',
      },
    },
  },
  variants: {},
  plugins: [],
};
